### ISSUE TITLE
Default config definition in another yaml

### ISSUE THREAD

**Issue by jeff1evesque** [genebean/genebean-winbind#11]
If I have the following hiera structure:

``` bash

---
# hiera.yaml

:backends:
  - yaml

:yaml:
  :datadir: /

:hierarchy:
  - vagrant/puppet/hiera/common
  - vagrant/puppet/hiera/another
```

Then, define the following `another.yaml`:

``` yaml
winbind::pam_require_membership_of :
  - 'mymembership'
winbind::smb_realm                 : 'AD.DIFFERENT.COM'
winbind::smb_workgroup             : 'AD2'
```

It appears the module will ignore the custom setting, and proceed with the following, since it was not set in the default `common.yaml`:
- `smb_realm` to `AD.EXAMPLE.COM`
- `smb_workgroup` to `AD`
- `pam_require_membership_of`:
  - 'sysadmins'
  - 'iso-scans'

If I move the configuration from `another.yaml` to `common.yaml`, it will be properly configured.

**Comment by westbywest** [comment]
The module isn't explicitly using any "hiera()" function, so its parameter lookup just uses native merging that puppet does for implicit hiera parameter lookup.  I.e. not a problem with the module, just standard puppet behavior.

If the intended behavior is for values specified in another.yaml, e.g. for winbind::pam_require_membership_of, to override those in common.yaml, then common.yaml needs to be at the bottom of the hierarchy.

**Comment by jeff1evesque** [comment]
If you have a multiple environments being managed by the puppetserver / puppetmaster, then it's likely to have several different yaml configurations for each.  Therefore, it may be likely to have the following `hiera.yaml`, where there would be multiple `winbind.yaml`, dedicated for each environment:

``` yaml
# hiera.yaml

:backends:
  - yaml

:yaml:
  :datadir: /

:hierarchy:
  - vagrant/puppet/hiera/common
  - vagrant/puppet/hiera/%{environment}/winbind
```

**Comment by jeff1evesque** [comment]
> If the intended behavior is for values specified in another.yaml, e.g. for winbind::pam_require_membership_of, to override those in common.yaml, then common.yaml needs to be at the bottom of the hierarchy.

There is no winbind related definition in `common.yaml`, and yet the configuration definitions from `winbind.yaml` is not being applied.  Maybe I missed something with my setup.

**Comment by jeff1evesque** [comment]
My [above](https://github.com/genebean/genebean-winbind/issues/11#issuecomment-249932511) case was a generalization of `:hierarchy: vagrant/puppet/hiera/environments/winbind`.  But, in my implementation I had a typo `environment`.

**Comment by westbywest** [comment]
Aha, upon seeing your "real" hiera.yaml, I see a possible cause. The %{environment} variable apparently isn't reliably parsed in hiera.yaml, either under certain circumstances or certain versions of puppet.  Never found a reasonable explanation why.  Try debugging a lookup with hiera -d or use the %{server_facts.environment} instead.  https://docs.puppet.com/hiera/3.2/hierarchy.html
