### ISSUE TITLE
Change package_ensure Default

### ISSUE THREAD

**Issue by yachub** [genebean/genebean-winbind#12]
I think we should consider changing the default value for the `package_ensure` parameter from `latest` to `present`. We experienced an issue that broke AD authentication for all RedHat 7 servers last night.

Apparently, when Puppet ensured samba-winbind from version 4.4 to 4.6 it required some modules/libraries from the latest kerberos packages, which are not hard dependencies because Kerberos _can be used_ in conjunction with samba-winbind, but is _not necessarily required_. If the packages had all updated at the same time, then there would have been no interruption. I think it would be best to change the default to prevent this from happening in the future.

Just FYI, the authentication broke without the winbind service being restarted, but this is the error message I receive after attempting to manually restart the service after _just_ the samba-winbind package was updated:

```
/usr/sbin/winbindd: relocation error: /usr/lib64/samba/libgse-samba4.so: symbol krb5_get_init_creds_opt_set_pac_request, version
 krb5_3_MIT not defined in file libkrb5.so.3 with link time reference
```

**Comment by yachub** [comment]
Please see PR #13 for change related to this issue.

**Note:** Do not merge using web interface, the hotfix branch was created using GitFlow and should be finished using GitFlow.

**Comment by yachub** [comment]
Just as a side note, even though its too late as this has already impacted RedHat 7, if we implement this change quickly before the same package updates are released for CentOS 7, then it will save everyone the same headache on CentOS.

**Comment by yachub** [comment]
PR #13 has been merged and the closing of this issue is pending the release of version 1.5.2.

**Comment by genebean** [comment]
1.5.2 got released but I forgot to clone this.
