### ISSUE TITLE
Example how to implement 'genebean-winbind'

### ISSUE THREAD

**Issue by jeff1evesque** [genebean/genebean-winbind#7]
Can the [`README.md`](https://github.com/genebean/genebean-winbind/blob/master/README.md) provide examples how to implement this module:
- command line
  - does the [usage](https://github.com/genebean/genebean-winbind#usage) section imply that everything the module offers can be run in the command line, or just the _Joining to AD_ portion?
- hiera
  - how does the [hiera](https://github.com/genebean/genebean-winbind#overview) file get included into a manifest implementing this module?
- manifest
  - how can a manifest implement this module (if not through hiera)?

**Comment by genebean** [comment]
Certainly, we will get this added over the next couple of days.

**Comment by jeff1evesque** [comment]
A few weeks ago, I thought this module was promising compared to the few I was reviewing.  However, I'm stuck on how to implement it.  So, I'm wondering if you have some examples of how to use this module?  I'd like to give it a shot this week.

**Comment by genebean** [comment]
I'll get this into the docs when I am back at a computer but here is how I use it at work: 

### Add something like this to all nodes you want bound to a domain

``` puppet
# baseline stuff
class profiles::base {
  # Used on selected OS only
  case $::kernel {
    Linux   : {
      include ::winbind

      $joindomain = $::osfamily ? {
        'RedHat' => 'joindomainForRedHat.sh',
        'Suse'   => 'joinDomainForSUSE.sh',
        default  => 'joindomainForRedHat.sh',
      }

      file { '/root/joinDomain.sh':
        ensure => present,
        mode   => '0755',
        source => "puppet:///modules/profiles/${joindomain}",
      }

    } # end Linux

    Windows : {
    }

    default : {
      fail("${::operatingsystem} is not supported.")
    }

  } # end case $::kernel
}
```

### Add this to your defaults in hiera

``` yaml
winbind::pam_require_membership_of :
  - 'sysadmins'
  - 'iso-scans'
winbind::smb_realm                 : 'AD.EXAMPLE.COM'
winbind::smb_workgroup             : 'AD'
```

### create scripts to be put in place by the profile above

The variations on the join domain script above are variations on this:

``` puppet
### This file is auto generated by Puppet ###
### Manual changes will be overwritten    ###

#!/bin/bash

username=$1

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 username"
  echo "Replace username with an account that can join this machine to the domain"
  exit 1
fi

# join domain with the name provided
net ads join -U $username
authconfig --enablemkhomedir --enablewinbind --enablewinbindauth --update
```

### use
1. Apply profile 
2. Run puppet 
3. Join domain using script in root's home directory 
4. Rerun puppet 
5. Enjoy

**Comment by genebean** [comment]
@jeff1evesque - did that info get you working?

**Comment by jeff1evesque** [comment]
Hi @genebean, I will try this coming Monday, or Tuesday at latest (thank you).  When you say _Run puppet_, does it mean puppet logic runs via puppet master, or `puppet apply`?

**Comment by genebean** [comment]
Unless you are running in a masterless environment you would want to do a `puppet agent -t` run. I will try to be more clear about that when I get it into the readme. Thanks for following up!

**Comment by jeff1evesque** [comment]
I'm running a self contained vagrant container for testing, in which case it's masterless. But, for non-testing environments, I would assume that a master implementation would make sense.

**Comment by genebean** [comment]
@jeff1evesque I believe we have gotten the needed examples into this as of v1.2.0. If not let me know and I'll reopen this for you.

**Comment by jeff1evesque** [comment]
How is `joindomainForRedHat.sh` created?  Is the following `joindomainForRedHat.sh`:

```bash
### This file is auto generated by Puppet ###
### Manual changes will be overwritten    ###

#!/bin/bash

username=$1

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 username"
  echo "Replace username with an account that can join this machine to the domain"
  exit 1
fi

# join domain with the name provided
net ads join -U $username
authconfig --enablemkhomedir --enablewinbind --enablewinbindauth --update
```

The docstring suggests that the above bash script creation is automated:

>
```bash
### This file is auto generated by Puppet ###
### Manual changes will be overwritten    ###
```

If so, how can I also automate this bash script creation?
